# Site settings
title: IES Des Moines
email: ''
description: "The Central Iowa IES section's vision is to build upon a century of outstanding excellence to create a premier lighting community that's dedicated to promoting the art and science of lighting to its members, allied profession organizations and to the public. We continually strive to uphold these efforts through educational programs, presentations, and social networking events."
baseurl: ""
url: "http://yourdomain.com"
highlighter: rouge

# Build settings
markdown: kramdown
permalink: pretty
